# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 11c8c46a736640475779526960c327d1311dbbe228d512bb16d0e89114acb44e4227db3029fe1f09071f7cead4cf8cb804d80a6400a997973884671f7f0581d8

test:
  secret_key_base: b6aa1ee650fa9f29b7d4b55906d6f963a21b0d135eeefa0dab08d1c5de489128a81022d28a13d9f98c98249d491085ab94943ca2dcc6b278d562393bb216dddd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
